@startuml 

'---Ocultar icono distintivo de la entidad
hide circle

'---Definición de entidades ---
'*Leer guia de estilos !!!
entity Profesor {
    PK id: int
    --
    nombreProfesor: string

}

entity Catedra {
    PK id: int
    --
    nombreCatedra: string

}

'----Relaciones-----
'Cero o uno	|o--
'Uno y solo uno	||--
'Cero o muchos	}o--
'Uno o muchos	}|--


'---Relacion entre entidades ---
Catedra }|--||  Profesor

@enduml