@startuml Catedra
hide circel
entity Alumno{
    -id<<PK>>: SERIAL
    -legajo: INT
    -documento: INT
    -catedraCursadas: INT
    -catedrasAprobadas: INT
    -nombre : STRING
    -apellido : STRING
    -correo : STRING
    -añoIngreso : INT
}

entity Aula{
    -id<<PK>>: SERIAL
    -numero: INT
    -capacidad: INT
    -ala: STRING
}
''Aula por No docente
entity AxND{
    -id<<PK>>: SERIAL
    -idAula<<FK>>: INT
    -idNoDocente<<FK>>: INT
}

entity Catedra{
    -id<<PK>>: SERIAL
    -descripcion: VARCHAR
    -idPlanEstudio<<FK>>: INT
    -idTurnoDeCursado<<FK>>: INT
}

''Catedra por alumno
entity CxAl{
    -id<<PK>>: SERIAL
    -idCatedra<<FK>>: INT
    -idAlumno<<FK>>: INT
}
''Catedra por docente por tipo docente
entity CxDxTD{
    -id<<PK>: SERIAL
    -idDxTD<<FK>>: INT
    -idCatedra<<FK>>: INT
    -idTipoDocente<<FK>>: INT
}
''Comision por aula
entity CxA{
    -id<<PK>>: SERIAL
    -idComision<<FK>>: INT
    -idAula<<FK>>: INT
}
''Catedra por Comisión
entity CxC{
    -id<<PK>>: SERIAL
    -idCatedra<<FK>>: INT
    -idComision<<FK>>: INT
}
''Catedra por Plan de Estudio
entity CxPE{
    -id<<PK>>: SERIAL
    -idCatedra<<FK>>: INT
    -idPlanEstudio<<FK>>: INT
}
entity Comision {
    -id<<PK>>: SERIAL
    -descripcion: VARCHAR
}
entity Departamento{
    -id<<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}
''Departamento por Docente
entity DxD{
    -id<<PK>>: SERIAL
    -idDepartamento<<FK>>: INT
    -idDocente<<FK>>: INT
}
entity Docente{
    -id<<PK>>: SERIAL
    -nombre: VARCHAR
    -apellido: VARCHAR
    -legajo: INT
}
entity InstanciaEvaluativa{
    -id <<PK>>: SERIAL
    -fechaEvaluacion: DATE
    -horaInicioEvaluacion: TIME?
    -horaFinEvaluacion: TIME?
    -idTipoEvaluacion<<FK>>: INT
}
''InstanciaEvaluativa por Alumno
entity IExA{
    -id<<PK>>: SERIAL
    -idInstanciaEvaluativa<<FK>>: INT
    -idAlumno<<FK>>: INT
}
entity TipoEvaluacion{
    -id<<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}
entity TipoDocente{
    -id<<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}
entity NoDocente{
    -id<<PK>>: SERIAL
    -nombre: VARCHAR
    -apellido: VARCHAR
    -legajo: INT
}
entity PlanEstudio{
    -id<<PK>>: SERIAL
    -añoPlan: DATE
    -descripcion: VARCHAR
}
entity TurnoDeCursado {
    -id<<PK>>: SERIAL
    -nombre: VARCHAR
    -descripcion: VARCHAR
}
entity CatedraxCorrelativa {
    -id<<PK>>
    -idCatedra<<FK>>
    ' warcrime?
    -idCatedraCorrelativa<<FK>>
}

Catedra ||--|{ CxC
Catedra ||--|{ CxAl
Catedra ||--|{ CxPE
Catedra ||--|{ CxDxTD
Catedra ||--|{ CatedraxCorrelativa
Catedra }|--|| TurnoDeCursado
Comision ||--|{ CxA
Comision ||--|{ CxC

Aula ||--|{ CxA
Aula ||--|{ AxND

NoDocente ||--|{ AxND

PlanEstudio ||--|{ CxPE
Alumno ||--|{ CxAl
Alumno ||--|{ IExA

Departamento ||--|{ DxD

Docente ||--|{ DxD
Docente ||-|{ CxDxTD
TipoDocente ||-|{ CxDxTD

InstanciaEvaluativa ||--{ IExA
InstanciaEvaluativa }|--||TipoEvaluacion

@enduml
