name: Invite User to Organization

on:
  issues:
    types: [opened]

jobs:
  invite:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, 'Invite User')
    steps:
      - name: Invite user to Organization and Team
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADMIN_PAT }}
          script: |
            const usernameMatch = context.payload.issue.body.match(/Username:\s*(\S+)/);
            const teamMatch = context.payload.issue.body.match(/Team:\s*(\S+)/);

            if (!usernameMatch || !teamMatch) {
              core.setFailed("Username or Team not found in issue body");
              return;
            }

            const username = usernameMatch[1];
            const teamSlug = teamMatch[1];

            console.log(`Inviting ${username} to organization...`);
            console.log(`Target organization: YOUR-ORG`);
            console.log(`Target team: ${teamSlug}`);
            console.log(`Inviting user: ${username}`);

            try {
              // Invitar al usuario a la organización
              await github.request('PUT /orgs/Sistema-Academico-2025/memberships/' + username, {
                role: 'member'
              });
              console.log(`Successfully invited ${username} to organization.`);
              
              // Agregar al equipo
              await github.request('PUT /orgs/Sistema-Academico-2025/teams/' + teamSlug + '/memberships/' + username, {
                role: 'member'
              });
              console.log(`Successfully added ${username} to team ${teamSlug}`);
            } catch (error) {
              console.error(`Error: ${error}`);
              core.setFailed(`Error: ${error.message}`);
            }
